apiVersion: v1
kind: Secret
metadata:
  name: linode-ddns
type: Opaque
stringData:
  LINODE_TOKEN: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: linode-ddns
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: linode-ddns
            image: jeffvader/linode-ddns
            env:
              - name: LINODE_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: linode-ddns
                    key: LINODE_TOKEN
              - name: DNS_HOSTNAME
                value: hostname.example.com
              - name: DEBUG
                value: "true"
            command: ['/linode-ddns']
          restartPolicy: OnFailure